test_that("use", {
  expect_silent(check_order("structure_iri"))
  expect_error(check_order("nonsense"))
  expect_error(check_order(NA))
  expect_error(check_order(NULL))
  expect_error(check_order(Inf))
  expect_error(check_order(""))
  expect_error(check_order(42))
  expect_error(check_order(-42))
  expect_error(check_order(3.14))
  expect_error(check_order(c()))
  expect_error(check_order(list()))
  expect_error(check_order(rep(0, 2)))
})
