test_that("use", {
  expect_silent(check_mhc_allele_names("cs.{HLA-A*01:01}"))
  expect_error(check_mhc_allele_names("nonsense"))
  expect_error(check_mhc_allele_names(NA))
  expect_error(check_mhc_allele_names(NULL))
  expect_error(check_mhc_allele_names(Inf))
  expect_error(check_mhc_allele_names(""))
  expect_error(check_mhc_allele_names(42))
  expect_error(check_mhc_allele_names(-42))
  expect_error(check_mhc_allele_names(3.14))
  expect_error(check_mhc_allele_names(c()))
  expect_error(check_mhc_allele_names(list()))
  expect_error(check_mhc_allele_names(rep(0, 2)))
})
