test_that("use", {
  expect_silent(check_table("mhc_search"))
  expect_silent(check_table("epitope_search"))
  expect_error(check_table("nonsense"))
  expect_error(check_table(NA))
  expect_error(check_table(NULL))
  expect_error(check_table(Inf))
  expect_error(check_table(""))
  expect_error(check_table(42))
  expect_error(check_table(3.14))
  expect_error(check_table(c()))
  expect_error(check_table(list()))
  expect_error(check_table(rep("eq.Linear peptide", 2)))
})
