test_that("use", {
  expect_silent(check_offset(0))
  expect_silent(check_offset(10000))
  expect_error(check_offset("nonsense"))
  expect_error(check_offset(NA))
  expect_error(check_offset(NULL))
  expect_error(check_offset(Inf))
  expect_error(check_offset(""))
  expect_error(check_offset(-42))
  expect_error(check_offset(3.14))
  expect_error(check_offset(c()))
  expect_error(check_offset(list()))
  expect_error(check_offset(rep(0, 2)))
})
