test_that("use", {
  expect_silent(check_verbose(TRUE))
  expect_silent(check_verbose(FALSE))
  expect_error(check_verbose("nonsense"))
  expect_error(check_verbose(NA))
  expect_error(check_verbose(NULL))
  expect_error(check_verbose(Inf))
  expect_error(check_verbose(""))
  expect_error(check_verbose(-42))
  expect_error(check_verbose(3.14))
  expect_error(check_verbose(c()))
  expect_error(check_verbose(list()))
  expect_error(check_verbose(c(TRUE, FALSE)))
})
