test_that("use", {
  expect_silent(check_max_n_queries(1))
  expect_silent(check_max_n_queries(10000))
  expect_silent(check_max_n_queries(Inf))
  expect_error(check_max_n_queries("nonsense"))
  expect_error(check_max_n_queries(NA))
  expect_error(check_max_n_queries(NULL))
  expect_error(check_max_n_queries(""))
  expect_error(check_max_n_queries(0))
  expect_error(check_max_n_queries(-42))
  expect_error(check_max_n_queries(3.14))
  expect_error(check_max_n_queries(c()))
  expect_error(check_max_n_queries(list()))
  expect_error(check_max_n_queries(rep(0, 2)))
})
