#' Get all valid values for `select`
#'
#' Get all valid values for `select`,
#' as checked by \link{check_select}
#' @return all valid values for `select`
#' @examples
#' get_selectors()
#' @author Richèl J.C. Bilderbeek
#' @export
get_selectors <- function() {
  c(
  "antibody_isotypes",
  "assay_iri_search",
  "assay_iris",
  "assay_names",
  "bcell_ids",
  "bcell_iris",
  "bcr_receptor_group_ids",
  "bcr_receptor_group_iris",
  "chebi_ids",
  "curated_source_antigens",
  "direct_ex_vivo_bool",
  "disease_iri_search",
  "disease_iris",
  "disease_names",
  "e_modification",
  "e_related_object_types",
  "elution_ids",
  "elution_iris",
  "host_organism_iri_search",
  "host_organism_iris",
  "host_organism_names",
  "iedb_assay_ids",
  "iedb_assay_iris",
  "journal_names",
  "linear_sequence",
  "linear_sequence_length",
  "mhc_allele_evidences",
  "mhc_allele_iri_search",
  "mhc_allele_iris",
  "mhc_allele_name",
  "mhc_allele_names",
  "mhc_allele_resolutions",
  "mhc_classes",
  "non_peptidic_molecule_iri_search",
  "non_peptidic_molecule_iris",
  "non_peptidic_molecule_names",
  "parent_source_antigen_iri_search",
  "parent_source_antigen_iris",
  "parent_source_antigen_names",
  "parent_source_antigen_source_org_iris",
  "parent_source_antigen_source_org_names",
  "pdb_ids",
  "pubmed_ids",
  "qualitative_measures",
  "r_object_source_molecule_iri_search",
  "r_object_source_molecule_iris",
  "r_object_source_molecule_names",
  "r_object_source_organism_iri_search",
  "r_object_source_organism_iris",
  "r_object_source_organism_names",
  "receptor_chain1_cdr1_seqs",
  "receptor_chain1_cdr2_seqs",
  "receptor_chain1_cdr3_seqs",
  "receptor_chain1_full_seqs",
  "receptor_chain1_types",
  "receptor_chain2_cdr1_seqs",
  "receptor_chain2_cdr2_seqs",
  "receptor_chain2_cdr3_seqs",
  "receptor_chain2_full_seqs",
  "receptor_chain2_types",
  "receptor_group_ids",
  "receptor_group_iris",
  "receptor_ids",
  "receptor_names",
  "receptor_types",
  "reference_authors",
  "reference_dates",
  "reference_ids",
  "reference_iris",
  "reference_titles",
  "reference_types",
  "source_organism_iri_search",
  "source_organism_iris",
  "source_organism_names",
  "structure_descriptions",
  "structure_id",
  "structure_iri",
  "structure_type",
  "submission_ids",
  "submission_iris",
  "tcell_ids",
  "tcell_iris",
  "tcell_irs",
  "tcr_receptor_group_ids",
  "tcr_receptor_group_iris"
  )
}
